
title: Powercraft
email: -info@powercraftgmbh.com
description: >- # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
github_username: UPMkuhn
baseurl: ''
url: '' # the base hostname & protocol for your site, e.g. http://example.com

sass:
  style: compressed
  load_paths:
    - assets/scss/
    - bower_components/bootstrap/scss/
  
plugins_dir:
    - jekyll-feed
    - jekyll-assets

# Build settings
markdown: kramdown
exclude: ['bower_components', 'node_modules']

#language settings
languages: ['en']
exclude_from_localizations: ['assets', 'dist', 'node_modules', '.sass-cache', 'bower_components']

#Collections
#collections_dir: components
collections:
  home:
    output: true


host: 0.0.0.0
livereload: false # You no longer need to include --livereload
reload_port: 5678 # If you don't want to use the default port

cdn:
  baseurl: true

source_maps: true
destination: "_site/"
compression: false
gzip: false
caching:
  path: ".jekyll-cache/assets"
  type: file
  enabled: true

assets:
  sources:
    - assets/dist
    - assets/scss
    - node_modules
  plugins:
    img:
      optim:
        {}
    css: 
      autoprefixer: {}

