#nginx to forward request 
jekyll:
  volumes:
    - './src:/jekyll'
  build: '.'
  ports:
    - "4500:4000"
  command: /bin/bash -c "bundle update listen && bundler install --full-index && jekyll clean && rm -rf .jekyll-cache && jekyll b"
  environment:
    - PORT=4000
web:
  image: crunchgeek/nginx-pagespeed
  volumes:
   - ./config/powercraft.conf:/etc/nginx/sites-enabled/powercraft.conf
   - ./config/.htaccess:/website/.htaccess
   - ./src/_site:/etc/nginx/html
   - ./logs:/siteLogs
  ports:
   - "8080:80"
  environment:
   - NGINX_HOST=martkin-kuhn.eu
   - NGINX_PORT=80
   - NGINX_PAGESPEED_IMG=on
   - NGINX_PAGESPEED_JS=on
   - NGINX_PAGESPEED_CSS=on
   - NGINX_PAGESPEED_STORAGE=files
   - NGINX_PAGESPEED=on


  command: /bin/bash -c "exec nginx -g 'daemon off;'"