#nginx to forward request 
jekyll:
  volumes:
    - './src:/jekyll'
  build: '.'
  ports:
    - "4500:4000"
  command: /bin/bash -c "bundle update listen && bundler install --full-index && jekyll clean && rm -rf .jekyll-cache && jekyll b"
  environment:
    - PORT=4000
web:
  image: nginx
  volumes:
   - ./config/:/etc/nginx
   - ./config/.htaccess:/website/.htaccess
   - ./src/_site:/website
   - ./logs:/siteLogs
  ports:
   - "8080:80"
  environment:
   - NGINX_HOST=martkin-kuhn.eu
   - NGINX_PORT=80
  command: /bin/bash -c "exec nginx -g 'daemon off;'"