#nginx to forward request 
jekyll:
  hostname: nginx
  volumes:
    - './src:/jekyll'
  build: '.'
  ports:
    - "8080:8080"
  environment:
    - PORT=80
web:
  image: nginx
  volumes:
   - ./config/:/etc/nginx
   - ./config/.htaccess:/website/.htaccess
   - ./src/_site:/website
   - ./logs:/siteLogs
  ports:
   - "80:80"
  environment:
   - NGINX_HOST=martkin-kuhn.eu
   - NGINX_PORT=80
  command: /bin/bash -c "exec nginx -g 'daemon off;'"